version: '3.8'

services:
  clan-sports-services:
    container_name: clan-sports-services
    restart: always
    build:
      context: .
      dockerfile: ./packages/services/.docker/Dockerfile.services
    ports:
      - '3001:3001'
  # clan-sports-frontend:
  #   container_name: clan-sports-frontend
  #   restart: always
  #   build:
  #     context: .
  #     dockerfile: ./packages/frontend/.docker/Dockerfile.frontend
  #   ports:
  #     - '80:3000'
