name: build_and_deploy_services

on:
  workflow_call:
    secrets:
      DOCKER_AUTH_TOKEN:
        description: 'Required docker auth token'
        required: true
  push:
    branches:
      - development

env:
  NODE_ENV: 'dev'
  SERVICE_NAME: 'clan.sports-services'
  DOCKER_USERNAME: 'codigouranio'
  AWS_DEFAULT_REGION: 'us-east-1'

jobs:
  build-service:
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: restore_or_save_cache
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-v1-dependencies-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-v1-dependencies-
      - run: npm ci
      - name: Run tests
        run: npm run services:test
      - name: Build docker image
        run: npm run services:docker:build
      - name: Login to DockerHub
        env:
          DOCKER_AUTH_TOKEN: ${{ secrets.DOCKER_AUTH_TOKEN }}
          DOCKER_USERNAME: ${{ env.DOCKER_USERNAME }}
        run: |
          echo "Authenticating docker.io"
          echo ${{ env.DOCKER_AUTH_TOKEN }} | docker login --username=${{ env.DOCKER_USERNAME }} --password-stdin
      - name: Push to DockerHub
        run: |
          docker push ${{ env.DOCKER_USERNAME }}/${{ env.SERVICE_NAME }}:latest

  deploy-service-production:
    needs: [build-service]
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: prerequisites
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'us-east-1'
        run: |
          aws configure set aws_access_key_id ${{ env.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws configure set default.region ${{ env.AWS_DEFAULT_REGION }}
          aws configure set region ${{ env.AWS_DEFAULT_REGION }}
      - name: Install essentials
        run: |
          aws --version
          sudo apt-get update && sudo apt-get -y install curl jq
          curl https://s3.us-west-2.amazonaws.com/lightsailctl/latest/linux-amd64/lightsailctl -o /usr/local/bin/lightsailctl
          chmod +x /usr/local/bin/lightsailctl
      - name: Release to Amazon Lightsail
        env:
          DOCKER_AUTH_TOKEN: ${{ secrets.DOCKER_AUTH_TOKEN }}
          DOCKER_USERNAME: ${{ env.DOCKER_USERNAME }}
          CONTAINER_IMAGE_NAME: ${{ env.DOCKER_USERNAME }}/${{ env.SERVICE_NAME }}:latest
          CONTAINER_SERVICE_NAME: service-${{ env.SERVICE_NAME }}
        run: |
          echo "Releasing to Amazon Lightsail"
          docker info

          echo "Authenticating docker.io"
          echo ${{ env.DOCKER_AUTH_TOKEN }} | docker login --username=${{ env.DOCKER_USERNAME }} --password-stdin

          docker pull ${{ env.CONTAINER_IMAGE_NAME }}

          # upload the docker image for this pipeline
          aws lightsail push-container-image \
            --service-name ${{ env.CONTAINER_SERVICE_NAME }}  \
            --label ${{ env.SERVICE_NAME }}-latest  \
            --image ${{ env.CONTAINER_IMAGE_NAME }}

          IMAGE_TAG=$(aws lightsail get-container-images --service $CONTAINER_SERVICE_NAME | jq -r .containerImages[0].image)

          # create a deployment with uploaded docker image
          aws lightsail create-container-service-deployment \
            --service-name $CONTAINER_SERVICE_NAME \
            --containers "{
              \"$CONTAINER_SERVICE_NAME\": {
                \"image\": \"$IMAGE_TAG\",
                \"environment\": {
                  \"NODE_ENV\": \"production\",
                  \"PGSSLMODE\": \"no-verify\"
                },
                \"ports\": {
                  \"80\": \"HTTP\"
                }
              }
            }" \
            --public-endpoint "{
              \"containerName\": \"$CONTAINER_SERVICE_NAME\",
              \"containerPort\": 80,
              \"healthCheck\": {
                \"path\": \"/healthcheck/liveness\",
                \"intervalSeconds\": 10
              }
            }"
